id: P006992
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG09761
  title: བྱ་རུང་ཁ་ཤོར་གྱི་ལོ་རྒྱུས
  author: ''
  volumes:
    b8765772b36e4485af7193e534cddb79:
      image_group_id: I00KG09843
      title: ''
      volume_number: 1
      total_pages: 142
ebook_metadata:
  title: བྱ་རུང་ཁ་ཤོར་གྱི་ལོ་རྒྱུས
  author: ''
  sku: P006992
  cover: cover.jpg
  layers:
  - pagination
