id: P006992
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:34:49.132336
source_metadata:
  id: bdr:W00KG09761
  title: བྱ་རུང་ཁ་ཤོར་གྱི་ལོ་རྒྱུས
  author: ''
  volumes:
    b93d3fc09b214b65a0e8b2f554bba82d:
      image_group_id: I00KG09843
      title: Volume 1 of bya rung kha shor gyi lo rgyus
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
