id: I91700720
legacy_id: P006992
ocr_import_info:
  bdrc_scan_id: W00KG09761
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T13:16:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:42:19.006374+00:00'
last_modified: 2022-08-29 20:42:34.348154
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG09761
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW00KG09761
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྱ་རུང་ཁ་ཤོར་གྱི་ལོ་རྒྱུས།
  author: ཁམས་སྤྲུལ་བསྟན་འཛིན་ཆོས་ཀྱི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.7492539187899212
  ocr_word_median_confidence_index: 0.8199999928474426
quality: null
bases:
  I00KG09843:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG09843
      total_pages: 142
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG09843.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7492539187899212
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
