id: I91700720
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:17:12+00:00'
last_modified: '2022-06-08T10:52:27.490501+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG09761
  title: བྱ་རུང་ཁ་ཤོར་གྱི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    22DF:
      image_group_id: I00KG09843
      title: Volume 1 of bya rung kha shor gyi lo rgyus
      total_pages: 142
      order: 1
      base_file: 22DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
